# TODO: remove this when Rust 1.85 is released
cargo-features = ["edition2024"]

[package]
name = "fearless_simd"
version = "0.2.0"
license = "MIT/Apache-2.0"
edition = "2024"
authors = ["Raph Levien <raph.levien@gmail.com>"]
keywords = ["simd"]
categories = ["hardware-support"]
description = "Safer and easier SIMD"
readme = "README.md"
rust-version = "1.85"

# TODO: remove this when Rust 1.85 is released
[language-server.rust-analyzer.server.extraEnv]
RUSTUP_TOOLCHAIN = "nightly"

[dependencies]
bytemuck = { version = "1.20", optional = true }
half = { version = "2.4.1", optional = true }
